from data import UnitType

# Adjacency list for territories
adjacency = {
    "Alaska": ["Kamchatka", "Territori del Nord Ovest", "Alberta"],
    "Alberta": ["Alaska", "Territori del Nord Ovest", "Ontario", "Stati Uniti Occidentali"],
    "America Centrale": ["Venezuela", "Stati Uniti Orientali", "Stati Uniti Occidentali"],
    "Stati Uniti Orientali": ["America Centrale", "Stati Uniti Occidentali", "Ontario", "Quebec"],
    "Groenlandia": ["Territori del Nord Ovest", "Ontario", "Quebec", "Islanda"],
    "Territori del Nord Ovest": ["Alaska", "Alberta", "Ontario", "Groenlandia"],
    "Ontario": ["Alberta", "Stati Uniti Occidentali", "Territori del Nord Ovest", "Stati Uniti Orientali", "Quebec", "Groenlandia"],
    "Quebec": ["Ontario", "Stati Uniti Orientali", "Groenlandia"],
    "Stati Uniti Occidentali": ["Alberta", "Ontario", "Stati Uniti Orientali", "America Centrale"],
    "Argentina": ["Perù", "Brasile"],
    "Brasile": ["Argentina", "Perù", "Venezuela", "Africa del Nord"],
    "Perù": ["Argentina", "Brasile", "Venezuela"],
    "Venezuela": ["Brasile", "Perù", "America Centrale"],
    "Gran Bretagna": ["Islanda", "Scandinavia", "Europa Settentrionale", "Europa Occidentale"],
    "Islanda": ["Groenlandia", "Gran Bretagna", "Scandinavia"],
    "Europa Settentrionale": ["Scandinavia", "Gran Bretagna", "Europa Occidentale", "Europa Meridionale", "Ucraina"],
    "Scandinavia": ["Islanda", "Gran Bretagna", "Europa Settentrionale", "Ucraina"],
    "Europa Meridionale": ["Europa Occidentale", "Europa Settentrionale", "Ucraina", "Medio Oriente", "Africa del Nord", "Egitto"],
    "Ucraina": ["Scandinavia", "Europa Settentrionale", "Europa Meridionale", "Medio Oriente", "Afghanistan", "Urali"],
    "Europa Occidentale": ["Gran Bretagna", "Europa Settentrionale", "Europa Meridionale", "Africa del Nord"],
    "Congo": ["Africa del Nord", "Africa Orientale", "Africa del Sud"],
    "Africa Orientale": ["Egitto", "Africa del Nord", "Congo", "Africa del Sud", "Madagascar"],
    "Egitto": ["Europa Meridionale", "Africa del Nord", "Africa Orientale", "Medio Oriente"],
    "Madagascar": ["Africa Orientale", "Africa del Sud"],
    "Africa del Nord": ["Europa Occidentale", "Europa Meridionale", "Brasile", "Egitto", "Congo", "Africa Orientale"],
    "Africa del Sud": ["Madagascar", "Africa Orientale", "Congo"],
    "Afghanistan": ["Ucraina", "Urali", "Cina", "Medio Oriente"],
    "Cina": ["Mongolia", "Siberia", "Urali", "Afghanistan", "Medio Oriente", "India", "Siam"],
    "India": ["Siam", "Medio Oriente", "Cina"],
    "Cita": ["Mongolia", "Siberia", "Jacuzia", "Kamchatka"],
    "Giappone": ["Kamchatka", "Mongolia"],
    "Kamchatka": ["Alaska", "Jacuzia", "Cita", "Mongolia", "Giappone"],
    "Medio Oriente": ["Europa Meridionale", "Egitto", "India", "Cina", "Afghanistan", "Ucraina"],
    "Mongolia": ["Cina", "Siberia", "Cita", "Kamchatka", "Giappone"],
    "Siam": ["Cina", "India", "Indonesia"],
    "Siberia": ["Jacuzia", "Cita", "Mongolia", "Cina", "Urali"],
    "Urali": ["Siberia", "Cina", "Afghanistan", "Ucraina"],
    "Jacuzia": ["Kamchatka", "Cita", "Siberia"],
    "Australia Orientale": ["Australia Occidentale", "Nuova Guinea"],
    "Indonesia": ["Siam", "Nuova Guinea", "Australia Occidentale"],
    "Nuova Guinea": ["Indonesia", "Australia Occidentale", "Australia Orientale"],
    "Australia Occidentale": ["Australia Orientale", "Nuova Guinea", "Indonesia"]
}

continents = {
    "America del Nord": ["Alaska","Alberta","America Centrale","Stati Uniti Orientali","Groenlandia","Territori del Nord Ovest","Ontario","Quebec","Stati Uniti Occidentali"],
    "America del Sud": ["Argentina","Brasile","Perù","Venezuela"],
    "Europa": ["Gran Bretagna","Islanda","Europa Settentrionale","Scandinavia","Europa Meridionale","Ucraina","Europa Occidentale"],
    "Africa": ["Congo","Africa Orientale","Egitto","Madagascar","Africa del Nord","Africa del Sud"],
    "Asia": ["Afghanistan","Cina","India","Cita","Giappone","Kamchatka","Medio Oriente","Mongolia","Siam","Siberia","Urali","Jacuzia"],
    "Oceania": ["Australia Orientale","Indonesia","Nuova Guinea","Australia Occidentale"]
}

continentsBonus = {
    "America del Nord": 5,
    "America del Sud": 2,
    "Europa": 5,
    "Africa": 3,
    "Asia": 7,
    "Oceania": 2
}

cardType = {
    "Alaska": UnitType.FANTE,
    "Alberta": UnitType.FANTE,
    "America Centrale": UnitType.CAVALLO,
    "Stati Uniti Orientali": UnitType.CANNONE,
    "Groenlandia": UnitType.CAVALLO,
    "Territori del Nord Ovest": UnitType.CANNONE,
    "Ontario": UnitType.CAVALLO,
    "Quebec": UnitType.CANNONE,
    "Stati Uniti Occidentali": UnitType.FANTE,
    "Argentina": UnitType.FANTE,
    "Brasile": UnitType.CANNONE,
    "Perù": UnitType.CAVALLO,
    "Venezuela": UnitType.CANNONE,
    "Gran Bretagna": UnitType.CAVALLO,
    "Islanda": UnitType.FANTE,
    "Europa Settentrionale": UnitType.CAVALLO,
    "Scandinavia": UnitType.CANNONE,
    "Europa Meridionale": UnitType.CAVALLO,
    "Ucraina": UnitType.CANNONE,
    "Europa Occidentale": UnitType.FANTE,
    "Congo": UnitType.CAVALLO,
    "Africa Orientale": UnitType.CANNONE,
    "Egitto": UnitType.FANTE,
    "Madagascar": UnitType.FANTE,
    "Africa del Nord": UnitType.FANTE,
    "Africa del Sud": UnitType.CANNONE,
    "Afghanistan": UnitType.FANTE,
    "Cina": UnitType.CAVALLO,
    "India": UnitType.FANTE,
    "Cita": UnitType.FANTE,
    "Giappone": UnitType.FANTE,
    "Kamchatka": UnitType.CAVALLO,
    "Medio Oriente": UnitType.CANNONE,
    "Mongolia": UnitType.CANNONE,
    "Siam": UnitType.CANNONE,
    "Siberia": UnitType.CANNONE,
    "Urali": UnitType.CAVALLO,
    "Jacuzia": UnitType.CAVALLO,
    "Australia Orientale": UnitType.FANTE,
    "Indonesia": UnitType.CAVALLO,
    "Nuova Guinea": UnitType.CAVALLO,
    "Australia Occidentale": UnitType.CANNONE
}

# Mapping between territory names and their corresponding image ID (01-42)
# TODO: Verify this mapping with the user
territoryImageMapping = {
    "Alaska": "07",
    "Alberta": "08",
    "America Centrale": "09",
    "Stati Uniti Orientali": "10",
    "Groenlandia": "11",
    "Territori del Nord Ovest": "12",
    "Ontario": "13",
    "Quebec": "14",
    "Stati Uniti Occidentali": "15",
    "Argentina": "16",
    "Brasile": "17",
    "Perù": "18",
    "Venezuela": "19",
    "Gran Bretagna": "32",
    "Islanda": "33",
    "Europa Settentrionale": "34",
    "Scandinavia": "35",
    "Europa Meridionale": "36",
    "Ucraina": "37",
    "Europa Occidentale": "38",
    "Congo": "01",
    "Africa Orientale": "02",
    "Egitto": "03",
    "Madagascar": "04",
    "Africa del Nord": "05",
    "Africa del Sud": "06",
    "Afghanistan": "20",
    "Cina": "21",
    "India": "22",
    "Cita": "23",
    "Giappone": "24",
    "Kamchatka": "25",
    "Medio Oriente": "26",
    "Mongolia": "27",
    "Siam": "28",
    "Siberia": "29",
    "Urali": "30",
    "Jacuzia": "31",
    "Australia Orientale": "39",
    "Indonesia": "40",
    "Nuova Guinea": "41",
    "Australia Occidentale": "42"
}